cfr/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from dashboard import views as dashboard_views
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from tastypie.api import Api
from api.resources import MapResource, LayerResource, IncidentResource, DisasterResource, \
    ValidationResource, GarbledIncidentResource, PhotoResource, AppPhotoResource, UserResource, IncidentLanguageTranslationResource, ProvinceResource, DistrictResource,\
    DsResource, GnResource, QuestionsResource, ChoicesResource, IncidentUserChoicesResource
#ValidationResource, GarbledIncidentResource, UserResource, PhotoResource

api = Api(api_name='v1')
api.register(MapResource())
api.register(LayerResource())
api.register(IncidentResource())
api.register(DisasterResource())
api.register(ValidationResource())
api.register(GarbledIncidentResource())
api.register(UserResource())
api.register(PhotoResource())
api.register(AppPhotoResource())
api.register(IncidentLanguageTranslationResource())
api.register(ProvinceResource())
api.register(DistrictResource())
api.register(DsResource())
api.register(GnResource())
api.register(QuestionsResource())
api.register(ChoicesResource())
api.register(IncidentUserChoicesResource())

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin', include(admin.site.urls)),
    url(r'^api/', include(api.urls)),
    url(r'^incidents/', include('incidents.urls', namespace='incidents')),
    url(r'^maps/', include('maps.urls', namespace='maps')),
    url(r'^charts/', include('charts.urls', namespace='charts')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^$', dashboard_views.index),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

incidents/urls.py
from django.conf.urls import url
from .tables import IncidentTable

from . import views
from .views import incident_list
from .models import Incident

urlpatterns = [
    url(r'^(?P<language>[\w\-]+)$', views.index, name='index'),
    url(r'^incident_form/(?P<language>[\w\-]+)$', views.incident_form, name='incident_form'),
    #url(r'^incident_list', incident_list.as_view(), name='incident_list'),
    url(r'^incident_list/', incident_list.as_view(), name='incident_list'),
    #url(r'^incident_list', incident_list, name='incident_list'),
    url(r'^incident_save/$', views.incident_save, name='incident_save'),
    url(r'^save_validation/$', views.save_validation, name='save_validation'),
    url(r'^incident_details/(?P<id>[\w\-]+)$', views.incident_details, name='incident_details'),
    url(r'^discard_incident/$', views.discard_incident, name='discard_incident'),
    url(r'^select_questions/$', views.select_questions, name='select_questions'),
    url(r'^send_email/$', views.send_email, name='send_email'),
    url(r'^incident_details_test/$', views.incident_details_test, name='incident_details_test'),
    url(r'^save_app_qs', views.save_app_qs, name='save_app_qs'),
    url(r'^send_mail_app/', views.send_mail_app, name='send_mail_app'),
    url(r'^upload_image/', views.upload_image, name='upload_image'),
    url(r'^image_link/(?P<id>[\w\-]+)$', views.image_link, name='image_link'),

]

incidents/models.py
from django.db import models
from users.models import MyUser

from django.conf import settings
import uuid

from settings.models import DisasterType
from django.forms import ModelForm


class Validation(models.Model):
    status = models.CharField(max_length=10, blank=True, null=True)
    validated_latitude = models.FloatField(blank=True, null=True)
    validated_longitude = models.FloatField(blank=True, null=True)
    comment = models.TextField(blank=True, null=True)
    date = models.DateTimeField(blank=True, null=True)
    user = models.ForeignKey(MyUser, blank=True, null=True)
    address = models.CharField(max_length=12, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'validation'


class Incident(models.Model):
    name = models.CharField(max_length=1000, blank=True, null=True)
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)
    disaster_type = models.ForeignKey(DisasterType, db_column='disaster_type', blank=True, null=True)
    contact_no = models.CharField(max_length=12, blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    synced_date = models.DateTimeField(blank=True, null=True)
    reported_date = models.DateTimeField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    validation = models.ForeignKey('Validation', unique=True, blank=True, null=True)
    #validation = models.ForeignKey(Validation, blank=True, null=True)
    district = models.CharField(max_length=12, blank=True, null=True)
    province = models.CharField(max_length=12, blank=True, null=True)
    ds = models.CharField(max_length=12, blank=True, null=True)
    is_validated = models.BooleanField((('1', '-----------'), (True, 'Yes'), (False, 'No')))

    class Meta:
        managed = False
        db_table = 'incident'

    #def __str__(self):
    #    return self.disaster_type.english + " reported by " + self.name


class CloseEndQs(models.Model):
    disaster_type = models.ForeignKey(DisasterType, db_column='disaster_type', blank=True, null=True)
    question = models.CharField(max_length=1000, blank=True, null=True)
    field_name = models.CharField(max_length=255, blank=True, null=True)
    field_type = models.CharField(max_length=255, blank=True, null=True)
    si = models.CharField(max_length=255, blank=True, null=True)
    ta = models.CharField(max_length=255, blank=True, null=True)
    #choices = models.ForeignKey('CloseEndQs', blank=True, null=True)

    def __str__(self):
        return self.question

    class Meta:
        managed = False
        db_table = 'close_end_qs'


class CloseEndQsChoice(models.Model):
    choice = models.CharField(max_length=1000, blank=True, null=True)
    question = models.ForeignKey(CloseEndQs, blank=True, null=True)
    id = models.AutoField(primary_key=True)
    si = models.CharField(max_length=255, blank=True, null=True)
    ta = models.CharField(max_length=255, blank=True, null=True)
    class Meta:
        managed = False
        db_table = 'close_end_qs_choices'


class Photo(models.Model):
    #name = models.CharField(max_length=1000, blank=True, null=True)
    incident = models.ForeignKey(Incident, blank=True, null=True)
    name = models.ImageField("Uploaded image", upload_to='uploaded')

    class Meta:
        managed = False
        db_table = 'photo'


class AppPhoto(models.Model):
    name = models.CharField(max_length=1000, blank=True, null=True)
    incident = models.ForeignKey(Incident, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'photo'


class SocialMediaIncident(models.Model):
    title = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    validation = models.ForeignKey(Validation, blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        managed = False
        db_table = 'social_media_incident'


class GarbledIncident(models.Model):
    name = models.CharField(max_length=1000, blank=True, null=True)
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)
    disaster_type = models.ForeignKey(DisasterType, db_column='disaster_type', blank=True, null=True)
    contact_no = models.CharField(max_length=12, blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    synced_date = models.DateTimeField(blank=True, null=True)
    reported_date = models.DateTimeField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    district = models.CharField(max_length=255, blank=True, null=True)
    province = models.CharField(max_length=255, blank=True, null=True)
    ds = models.CharField(max_length=255, blank=True, null=True)
    user = models.ForeignKey(MyUser, db_column='user', blank=True, null=True)
    deleted_date = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'garbled_incident'


class IncidentLanguageTranslation(models.Model):
    language = models.CharField(max_length=255, blank=True, null=True)
    incident_report_header = models.CharField(max_length=255, blank=True, null=True)
    incident_report_quote = models.CharField(max_length=1000, blank=True, null=True)
    inform_disaster = models.CharField(max_length=255, blank=True, null=True)
    click_to_get_location = models.CharField(max_length=255, blank=True, null=True)
    cancel = models.CharField(max_length=255, blank=True, null=True)
    incident = models.CharField(max_length=50, blank=True, null=True)
    successful_msg = models.CharField(max_length=100, blank=True, null=True)
    ok = models.CharField(max_length=10, blank=True, null=True)
    submit = models.CharField(max_length=255, blank=True, null=True)
    gps_location = models.CharField(max_length=255, blank=True, null=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    contact_no = models.CharField(max_length=255, blank=True, null=True)
    disaster_type = models.CharField(max_length=255, blank=True, null=True)
    description = models.CharField(max_length=255, blank=True, null=True)
    images = models.CharField(max_length=255, blank=True, null=True)
    data_collection_form = models.CharField(max_length=255, blank=True, null=True)
    location_error_msg = models.CharField(max_length=255, blank=True, null=True)
    contact_no_validity_msg = models.CharField(max_length=255, blank=True, null=True)
    disaster_error_msg = models.CharField(max_length=255, blank=True, null=True)
    next = models.CharField(max_length=255, blank=True, null=True)
    map = models.CharField(max_length=255, blank=True, null=True)
    previous = models.CharField(max_length=255, blank=True, null=True)
    previous = models.CharField(max_length=255, blank=True, null=True)
    map_legend = models.CharField(max_length=255, blank=True, null=True)
    drop_down_select_display = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'incident_language_translation'


class IncidentUserChoices(models.Model):
    question = models.ForeignKey(CloseEndQs, blank=True, null=True)
    choice = models.ForeignKey(CloseEndQsChoice, blank=True, null=True)
    incident = models.ForeignKey(Incident, blank=True, null=True)
    text_input = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'incident_user_choices'

incidents/forms.py
from django import forms
from .models import Incident


class IncidentForm(forms.ModelForm):

    class Meta:
        model = Incident
        fields = ('name', 'longitude', 'latitude', 'disaster_type', 'contact_no',
                  'address', 'description')

incidents/templates/incidents/dynamic_form.html
<div></div>

incidents/templates/incidents/incident_main.html
{% extends "dashboard/site_header.html" %}

{% load static %}

{% block content %}
{% load render_table from django_tables2 %}


    <script>
$(document).ready(function(){
    $('#id_reported_date_0').prop({type:"date"});
    $('#id_reported_date_1').prop({type:"date"});
});
    </script>
<style>
    .table-container {width:100%;}
</style>
<style>
input[type=text], select {
    width: 35%;
    padding: 5px 5px;
    margin: 8px 0;

    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
}

input[type=date] {
    width: 35%;
    padding: 5px 5px;
    margin: 8px 0;

    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
}

input[type=submit] {
    width: 20%;
    background-color: #4CAF50;
    color: white;
    padding: 5px 5px;
    margin: 8px 0;
    margin-left:130px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
}

input[type=submit]:hover {
    background-color: #45a049;
}

#id_name {margin-left:90px;}
#id_disaster_type {margin-left:45px;}
#id_validation {margin-left:32px;}
#id_reported_date_0 {width:15%;margin-left:38px;}
#id_reported_date_1 {width:15%;margin-left:38px;}
#id_district {margin-left:80px;}
#id_is_validated {margin-left:55px;}
.helptext {display:none;}
</style>



        <!-- page content -->
        <div class="right_col" role="main">
            <div class="">

                <div class="clearfix"></div>

                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="x_panel">
                            <div class="x_title">
                                <h2>Reported Incidents</h2>
                                <ul class="nav navbar-right panel_toolbox">
                                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                    </li>

                                </ul>
                                <div class="clearfix"></div>
                            </div>
                            <div class="x_content">
                                <div class="col-md-8">

                                </div>
                                <div class="col-md-9">

                                </div>
                                <br><br>
                                {% if table %}
                                <form method='GET'>
                                    {{ filter.form }}
                                    <input type='submit' class='btn btn-primary' value='Filter'/>

                                     <br><br>
                                    Displaying {{ filter.qs.count }} of {{ filter.queryset.count }} items.
                                    |

                                    <a href='{{ request.path }}'>Clear</a>
                                </form>

                                     {% render_table table %}
                                {% else %}
                                    No records found
                                {% endif %}
                            </div>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /page content -->

   {% endblock %}

incidents/templates/incidents/incident_main_v4.html
{% load static %}
{% load render_table from django_tables2 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>CFR</title>

    <!-- Bootstrap -->
    <link href="{% static 'incidents/vendors/bootstrap/dist/css/bootstrap.min.css'%} " rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'incidents/vendors/font-awesome/css/font-awesome.min.css'%}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'incidents/vendors/nprogress/nprogress.css'%}" rel="stylesheet">
    <link href="vendors/openlayers/ol.css" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="{% static 'incidents/css/custom.css'%}" rel="stylesheet">
         <link href="{% static 'incidents/css/screen.css'%}" rel="stylesheet">
    <script src="{% static 'incidents/vendors/jquery/dist/jquery.min.js'%}"></script>
    <script>
$(document).ready(function(){
    $('#id_reported_date_0').prop({type:"date"});
    $('#id_reported_date_1').prop({type:"date"});
});
    </script>
<style>
    .table-container {width:100%;}
</style>
<style>
input[type=text], select {
    width: 35%;
    padding: 5px 5px;
    margin: 8px 0;

    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
}

input[type=date] {
    width: 35%;
    padding: 5px 5px;
    margin: 8px 0;

    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
}

input[type=submit] {
    width: 20%;
    background-color: #4CAF50;
    color: white;
    padding: 5px 5px;
    margin: 8px 0;
    margin-left:130px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
}

input[type=submit]:hover {
    background-color: #45a049;
}

#id_name {margin-left:90px;}
#id_disaster_type {margin-left:45px;}
#id_validation {margin-left:32px;}
#id_reported_date_0 {width:15%;margin-left:38px;}
#id_reported_date_1 {width:15%;margin-left:38px;}
#id_district {margin-left:80px;}
#id_is_validated {margin-left:55px;}
.helptext {display:none;}
</style>

</head>

<body class="nav-md">
<div class="container body">
    <div class="main_container">
        <div class="col-md-3 left_col">
            <div class="left_col scroll-view">
                <div class="navbar nav_title" style="border: 0;">
                    <a href="index.html" class="site_title"><i class="fa fa-map-marker"></i> <span>CFR</span></a>
                </div>

                <div class="clearfix"></div>

                <!-- menu profile quick info -->
                <div class="profile">
                    <div class="profile_pic">
                        <img src="{% static 'incidents/images/img.png'%}" alt="..." class="img-circle profile_img">
                    </div>
                    <div class="profile_info">
                        <span>Welcome,</span>
                        <h2>Admin</h2>
                    </div>
                </div>
                <!-- /menu profile quick info -->

                <br/>
                <!-- sidebar menu -->
                <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                    <div class="menu_section">
                        <h3 style="color:#898989;">----------------------------------------</h3>
                        <ul class="nav side-menu">
                            <li><a href="index.html"><i class="fa fa-home"></i> Dashboard </a>

                            </li>
                            <li><a href="map.html"><i class="fa fa-edit"></i> Disaster Map </a>

                            </li>
                            <li><a><i class="fa fa-desktop"></i> User Manegment <span class="fa fa-chevron-down"></span></a>
                                <ul class="nav child_menu">
                                    <li><a href="add_user.html">Add User</a></li>
                                    <li><a href="profile.html">Profile</a></li>
                                    <li><a href="user_maneger.html">Manage Users</a></li>

                                </ul>
                            </li>
                            <!--li><a href="add_disaster.html"><i class="fa fa-table"></i> Add Disaster </a-->

                            </li>
                            <li><a href="incedent.html"><i class="fa fa-table"></i> Incedents </a>

                            </li>
                            <li><a href="charts.html"><i class="fa fa-table"></i> Charts </a>

                            </li>


                        </ul>
                    </div>


                </div>
                <!-- /sidebar menu -->


            </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
            <div class="nav_menu">
                <nav>
                    <div class="nav toggle">
                        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                    </div>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="">
                            <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown"
                               aria-expanded="false">
                                <img src="{% static 'incidents/images/img.png'%}" alt="">Admin
                                <span class=" fa fa-angle-down"></span>
                            </a>
                            <ul class="dropdown-menu dropdown-usermenu pull-right">
                                <li><a href="javascript:;"> Profile</a></li>

                                <li><a href="javascript:;">Help</a></li>
                                <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                            </ul>
                        </li>

                        <li role="presentation" class="dropdown">
                            <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown"
                               aria-expanded="false">
                                <i class="fa fa-envelope-o"></i>
                                <span class="badge bg-green">6</span>
                            </a>
                            <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                                <li>
                                    <a>
                                        <span class="image"><img src="{% static 'incidents/images/img.png"
                                                                 alt="Profile Image"/></span>
                        <span>
                          <span>Admin User</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a>
                                        <span class="image"><img src="{% static 'incidents/images/img.png'%}"
                                                                 alt="Profile Image"/></span>
                        <span>
                          <span>Admin User</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a>
                                        <span class="image"><img src="{% static 'incidents/images/img.png'%}"
                                                                 alt="Profile Image"/></span>
                        <span>
                          <span>Admin User</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a>
                                        <span class="image"><img src="{% static 'incidents/images/img.png'%}"
                                                                 alt="Profile Image"/></span>
                        <span>
                          <span>Admin User</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                        </span>
                                    </a>
                                </li>
                                <li>
                                    <div class="text-center">
                                        <a>
                                            <strong>See All Messages</strong>
                                            <i class="fa fa-angle-right"></i>
                                        </a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
            <div class="">

                <div class="clearfix"></div>

                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="x_panel">
                            <div class="x_title">
                                <h2>Reported Incidents</h2>
                                <ul class="nav navbar-right panel_toolbox">
                                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                    </li>

                                </ul>
                                <div class="clearfix"></div>
                            </div>
                            <div class="x_content">
                                <div class="col-md-8">

                                </div>
                                <div class="col-md-9">

                                </div>
                                <br><br>
                                {% if table %}
                                <form method='GET'>
                                    {{ filter.form }}
                                    <input type='submit' class='btn btn-primary' value='Filter'/>

                                     <br><br>
                                    Displaying {{ filter.qs.count }} of {{ filter.queryset.count }} items.
                                    |

                                    <a href='{{ request.path }}'>Clear</a>
                                </form>

                                     {% render_table table %}
                                {% else %}
                                    No records found
                                {% endif %}
                            </div>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /page content -->

    <!-- footer content -->
    <footer>
        <div class="pull-right">
            CFR Developed by <a href="https://geoedge.lk">GeoEDGE</a>
        </div>
        <div class="clearfix"></div>
    </footer>
    <!-- /footer content -->
</div>
</div>


<!-- Bootstrap -->
<script src="{% static 'incidents/vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'incidents/vendors/fastclick/lib/fastclick.js' %}"></script>
<!-- NProgress -->
<script src="{% static 'incidents/vendors/nprogress/nprogress.js' %}"></script>

<!-- Custom Theme Scripts -->
<script src="{% static 'incidents/js/custom.js' %}"></script>
</body>
</html>

incidents/templates/incidents/index.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">

    <title>CFR</title>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- The CSS
    ================================================== -->
    <link href="{% static 'incidents/css/theme.css' %}" rel="stylesheet">
    <link href="{% static 'incidents/css/animate.min.css' %}" rel="stylesheet">

</head>

<body style="overflow-x:hidden;">
<!-- Preloader -->
<div id="preloader">
    <div id="status">&nbsp;</div>
</div>
<!-- The Navbar -->
<!-- Navbar Section -->
<div class="wrapper wrapper-navbar wrapper-no-padding wrapper-fixed  wrapper-transparent"
     data-0="background-color:rgba(0,0,0,0);border-bottom:1px solid rgba(255,255,255,.12);"
     data-150="background-color:rgba(0,0,0,.9);border-bottom:1px solid rgba(255,255,255,0);">
    <nav class="navbar navbar-inverse navbar-transparent">
        <div class="container">
            <div class="navbar-header" style="width:100%;">

                <a class="navbar-brand font-sm" href="index.html"><img src="{% static 'incidents/img/logo.png' %}"
                                                                       style="width:80px;"
                                                                       alt=""></a>
                <span id="span" style="float:right;" class="navbar-brand font-sm">
                    <a href="{% url 'incidents:index' 'en' %}" style="color:#fff;text-decoration:none;">
                        English </a>|
                    <a style="color:#fff;text-decoration:none;" href="{% url 'incidents:index' 'si' %}"> සිංහල </a>|
                    <a style="color:#fff;text-decoration:none;" href="{% url 'incidents:index' 'ta' %}"> தமிழ் </a>
                </span>
            </div>

        </div><!-- /.container-fluid -->
    </nav>
</div>

<!-- The Hero Wrapper -->

<div class="wrapper wrapper-gradient wrapper-no-padding wrapper-darkest wrapper-overflow-hidden">
    <div class="overlay"></div>
    <div class="container" id="bck-img10">
        <div class="row">
            <div class="col-xs-6 wrapper-xxl">

                <h2 class="headline">{{ language_translations.incident_report_header }}</h2>
                <p class="lead">{{ language_translations.incident_report_quote }}</p>
                <a class="btn btn-lg btn-success" href="{% url 'incidents:incident_form' language %}"><i class="fa fa-hand-o-down"></i>
                    {{ language_translations.inform_disaster }}
                </a>
            </div>
        </div>
    </div>

</div>

<!-- All core JavaScript
================================================== -->

<script src="{% static 'incidents/js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'incidents/js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'incidents/js/smoothscroll.min.js' %}" type="text/javascript"></script>
<script src="{% static 'incidents/js/skrollr.min.js' %}" type="text/javascript"></script>


<script>
$(document).ready(function(){
  $(document).ready(function(){
            $(".dropdown-menu li a").click(function(){
            $("#options").text($(this).text());
            });
        });
});


</script>

<!-- Init the parallax script - if you don´t load it above remove it here too -->
<script type="text/javascript">
       var s = skrollr.init();


</script>

<!-- Preloader -->
<script type="text/javascript">

            $(window).load(function() { // makes sure the whole site is loaded
                $('#status').fadeOut(); // will first fade out the loading animation
                $('#preloader').delay(350).fadeOut('slow'); // will fade out the white DIV that covers the website.
                $('body').delay(350).css({'overflow':'visible'});
            })



</script>

</body>
</html>