cfr/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from dashboard import views as dashboard_views
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from tastypie.api import Api
from api.resources import MapResource, LayerResource, IncidentResource, DisasterResource, \
    ValidationResource, GarbledIncidentResource, PhotoResource, AppPhotoResource, UserResource, IncidentLanguageTranslationResource, ProvinceResource, DistrictResource,\
    DsResource, GnResource, QuestionsResource, ChoicesResource, IncidentUserChoicesResource
#ValidationResource, GarbledIncidentResource, UserResource, PhotoResource

api = Api(api_name='v1')
api.register(MapResource())
api.register(LayerResource())
api.register(IncidentResource())
api.register(DisasterResource())
api.register(ValidationResource())
api.register(GarbledIncidentResource())
api.register(UserResource())
api.register(PhotoResource())
api.register(AppPhotoResource())
api.register(IncidentLanguageTranslationResource())
api.register(ProvinceResource())
api.register(DistrictResource())
api.register(DsResource())
api.register(GnResource())
api.register(QuestionsResource())
api.register(ChoicesResource())
api.register(IncidentUserChoicesResource())

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin', include(admin.site.urls)),
    url(r'^api/', include(api.urls)),
    url(r'^incidents/', include('incidents.urls', namespace='incidents')),
    url(r'^maps/', include('maps.urls', namespace='maps')),
    url(r'^charts/', include('charts.urls', namespace='charts')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^$', dashboard_views.index),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reports/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^report/(?P<filter_type>[\w\-]+)/$', views.report, name='report'),
    url(r'^inc_date_data/(?P<filter_query>[\w\-]+)$', views.inc_date_data, name='inc_date_data')
]

reports/models.py
from django.db import models

# Create your models here.

reports/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_protect, csrf_exempt

from incidents.models import Incident
from administrative_divisions.models import District
from django.core import serializers
from django.core.serializers.json import DjangoJSONEncoder
from django.db.models import Count
import json
import datetime
from django.conf import settings
from datetime import date
import os

import csv
from django.utils import six
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import user_passes_test


def permission_required(perm, login_url=None, raise_exception=True):
    def check_perms(user):
        if isinstance(perm, six.string_types):
            perms = (perm, )
        else:
            perms = perm
        if user.has_perms(perms):
            return True
        if raise_exception and user.pk:
            raise PermissionDenied
        return False
    return user_passes_test(check_perms, login_url=login_url)


@permission_required('incidents.access_report_page', login_url='/admin/login/')
def index(request):
    return render(request, 'reports/reports_main.html')


def report(request, filter_type):

    disaster_list = District.objects.all()

    context = {
        'filter_type': filter_type,
        'districts': disaster_list
    }

    return render(request, 'reports/reports.html', context)


@csrf_exempt
def inc_date_data(request, filter_query):
    report_data = None
    post_data = json.loads(request.body)
    from_date = post_data['from_date']
    end_date = post_data['end_date']
    is_export = post_data['is_export']
    csv_headers = None

    from_date = datetime.datetime.strptime(from_date, "%Y-%m-%d").date()
    end_date = datetime.datetime.strptime(end_date, "%Y-%m-%d").date()

    if filter_query == 'date_icount':
        report_data = Incident.objects.filter(reported_date__range=(from_date, end_date)).\
            extra(select={'date': 'DATE(reported_date)'}).values('date').annotate(count=Count('id')).order_by('-count')
        csv_headers = ['Date', 'Count']

    elif filter_query == 'district_disaster':
        district = post_data['district']
        report_data = Incident.objects.filter(district=district).\
            values('district', 'disaster_type__english')\
            .annotate(count=Count('id')).order_by('-count')
        csv_headers = ['Disaster Type', 'Count']

    if is_export:

        response = HttpResponse('', content_type='application/x-download;charset=utf-8')
        response['Content-Disposition'] = 'attachment; filename="books.xls"'

        writer = csv.writer(response)

        writer.writerow(csv_headers)
        for row in report_data:
            if filter_query == 'date_icount':
                writer.writerow([row['date'], row['count']])
            else:
                writer.writerow([row['disaster_type__english'], row['count']])

        return response
    else:
        return HttpResponse(json.dumps(list(report_data), cls=DjangoJSONEncoder), content_type='application/json')

reports/templates/reports/reports.html
{% extends "dashboard/site_header.html" %}

{% load static %}

{% block content %}

 <link href="{% static 'dashboard/vendors/angularPrint/angularPrint.css' %}" rel="stylesheet">
<style>
.form-horizontal .control-label {text-align:left;}
.btn .dropdown-toggle .btn-default {border-radius:0;}
#title {visibility:hidden;display:none}



</style>


<!-- page content -->
<div class="right_col" role="main" ng-app="reportApp" ng-controller="ReportController">
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Reports</h2>
                    <ul class="nav navbar-right panel_toolbox">


                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>


                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content" style="min-height:480px;">
                    <div class="">


                        <div class="col-md-4">


                            <form class="form-horizontal">
                                <fieldset>

                                    {% if filter_type == 'date_icount' %}
                                    <div class="form-group">
                                        <label class="col-md-2 control-label" for="textinput">Date</label>
                                        <div class="col-md-10">
                                            <input type="text" id="daterange" name="daterange"
                                                   class="form-control"
                                            />
                                            <i class="glyphicon glyphicon-calendar form-control-feedback"
                                               style="margin-right:5px;margin-top:5px;"></i>
                                        </div>
                                    </div>
                                    {% endif %}

                                    {% if filter_type == 'district_disaster' %}
                                    <div class="form-group">
                                        <label class="col-md-2 control-label" for="selectbasic">District</label>
                                        <div class="col-md-10">
                                            <select ng-model="selectedDistrict" class="form-control"
                                            >
                                                {% for ditrict in districts %}
                                                <option value="{{ ditrict.name }}">{{ ditrict.name }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                    </div>
                                    {% endif %}

                                    <!-- Button (Double) -->
                                    <div class="form-group">
                                        <label class="col-md-2 control-label" for="button1id"></label>
                                        <div class="col-md-10">
                                            <button id="load_data" ng-click="loadData('{{ filter_type }}')"
                                                    name="button1id" class="btn btn-success">
                                                Load Data
                                            </button>
                                            <button id="button2id" name="button2id" class="btn btn-default">
                                                Clear
                                            </button>

                                        </div>
                                    </div>

                                </fieldset>
                            </form>


                        </div>
                        <div class="col-md-8">
                            <div print-section>
                                        <span class="printOnly" id="title">
                                    {% if filter_type == 'district_disaster' %}
                                  <h4 id="incident_district_header"></h4>
                                        {% elif filter_type == 'date_icount' %}
                                        <h4 id="incident_date_header">Date</h4>
                                    {% endif %}
                                            <hr>
                                            </span>
                                <table print-section ng-if="filter_data.length"
                                       class="table table-bordered table-striped table-hover">
                                    <thead>
                                    <tr>
                                        <th ng-bind="table_head_1">
                                        </th></th>
                                        <th ng-bind="table_head_2">
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% if filter_type == 'district_disaster' %}
                                    <tr ng-repeat="row in filter_data">
                                        <td ng-bind="row.disaster_type__english">
                                        </td>
                                        <td ng-bind="row.count">
                                        </td>
                                    </tr>
                                    {% endif %}
                                    {% if filter_type == 'date_icount' %}
                                    <tr ng-repeat="row in filter_data">
                                        <td ng-bind="row.date">
                                        </td>
                                        <td ng-bind="row.count">
                                        </td>
                                    </tr>
                                    {% endif %}

                                    </tbody>
                                </table>
                            </div>
                            <button ng-click="report_export('{{ filter_type }}')" class="btn btn-info">Export
                                Data
                            </button>
                            <button print-btn class="btn btn-info">Print
                                Report
                            </button>

                        </div>
                    </div>


                </div>
                <!-- /page content -->


                <script>
                var init_start_date = moment().subtract(20, 'days').format('MM/DD/YYYY');
                var init_end_date = moment().format('MM/DD/YYYY');

                var start_date = moment().subtract(20, 'days').format('YYYY-MM-DD');
                var end_date = moment().format('YYYY-MM-DD');

                $('#incident_date_header').text('Report for Incident count Vs. Date range of ('+ start_date+' - '+end_date+')');

                $(function() {

                    if('{{ filter_type }}' == 'date_icount'){
                    $('input[name="daterange"]').daterangepicker(
                    {startDate: init_start_date,
                    endDate: init_end_date,
                    },
                    function(start, end, label) {
                        start_date = start.format('YYYY-MM-DD');
                        end_date = end.format('YYYY-MM-DD');
                        $('#incident_date_header').text('Report for Incident count Vs. Date range of ('+ start_date+' - '+end_date+')');
                    });

                   $('#daterange').data('daterangepicker').setStartDate(init_start_date);
                    $('#daterange').data('daterangepicker').setEndDate(init_end_date);

                    }

                  $('.selectpicker').on('change', function(){
                    var selected = $(this).val();

                  });


                });




                </script>
                </div></div></div></div>
                {% endblock %}

reports/templates/reports/reports_main.html
{% extends "dashboard/site_header.html" %}

{% load static %}

{% block content %}
    <style>
.form-horizontal .control-label {text-align:left;}
.btn .dropdown-toggle .btn-default {border-radius:0;}

    </style>



        <!-- page content -->
        <div class="right_col" role="main">
            <div class="row">
                <div class="col-md-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Reports</h2>
                            <ul class="nav navbar-right panel_toolbox">

                               

                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>


                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content" style="min-height:480px;">

                         
						<div class="col-md-6">
						 <center>
						<a href="{% url 'reports:report' 'date_icount' %}">
						<img src="{% static 'reports/img/calendar-icon-300x300.jpg' %}" alt="..." style="width:150px;" class="">
						<h4>  Tabular Data count Vs. Date</h4>
						</a>
						</center>
						</div>
						
						<div class="col-md-6">
						 <center>
						<a href="{% url 'reports:report' 'district_disaster' %}">
						<img src="{% static 'reports/img/Google-Maps-icon.png' %}" alt="..." style="width:150px;" class="">
						 <h4>  Tabular Data count Vs. District</h4>
						</a>
						</center>
						</div>
						
						
                        </div>
                        <!-- /page content -->
</div></div></div></div>
                     {% endblock %}

reports/templates/reports/reports_main_v1.html
{% load static %}

<!DOCTYPE html>
<html lang="en" ng-app="reportApp">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>CFR</title>

    <!-- Bootstrap -->
    <link href="{% static 'reports/vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'reports/vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'reports/vendors/nprogress/nprogress.css' %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'reports/css/custom.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'reports/css/bootstrap-select.min.css' %}">


    <script src="{% static 'reports/vendors/openlayers/ol.js' %}"></script>
    <style>
.form-horizontal .control-label {text-align:left;}
.btn .dropdown-toggle .btn-default {border-radius:0;}

    </style>
</head>

<body ng-controller="ReportController" class="nav-md">
<div class="container body">
    <div class="main_container">
        <div class="col-md-3 left_col">
            <div class="left_col scroll-view">
                <div class="navbar nav_title" style="border: 0;">
                    <a href="index.html" class="site_title"><i class="fa fa-map-marker"></i> <span>CFR</span></a>
                </div>

                <div class="clearfix"></div>

                <!-- menu profile quick info -->
                <div class="profile">
                    <div class="profile_pic">
                        <img src="{% static 'reports/img/img.png' %}" alt="..." class="img-circle profile_img">
                    </div>
                    <div class="profile_info">
                        <span>Welcome,</span>
                        <h2>Admin</h2>
                    </div>
                </div>
                <!-- /menu profile quick info -->

                <br/>
                <!-- sidebar menu -->
                <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                    <div class="menu_section">
                        <h3 style="color:#898989;">----------------------------------------</h3>
                        <ul class="nav side-menu">
                            <li><a href="index.html"><i class="fa fa-home"></i> Dashboard </a>

                            </li>
                            <li><a href="map.html"><i class="fa fa-edit"></i> Disaster Map </a>

                            </li>
                            <li><a><i class="fa fa-desktop"></i> User Manegment <span class="fa fa-chevron-down"></span></a>
                                <ul class="nav child_menu">
                                    <li><a href="add_user.html">Add User</a></li>
                                    <li><a href="profile.html">Profile</a></li>
                                    <li><a href="user_maneger.html">Manage Users</a></li>

                                </ul>
                            </li>
                            <!--li><a href="add_disaster.html"><i class="fa fa-table"></i> Add Disaster </a-->

                            </li>
                            <li><a href="incedent.html"><i class="fa fa-table"></i> Incedents </a>

                            </li>
                            <li><a href="charts.html"><i class="fa fa-table"></i> Charts </a>

                            </li>


                        </ul>
                    </div>


                </div>
                <!-- /sidebar menu -->


            </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
            <div class="nav_menu">
                <nav>
                    <div class="nav toggle">
                        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                    </div>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="">
                            <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown"
                               aria-expanded="false">
                                <img src="{% static 'reports/img/img.png' %}" alt="">Admin
                                <span class=" fa fa-angle-down"></span>
                            </a>
                            <ul class="dropdown-menu dropdown-usermenu pull-right">
                                <li><a href="javascript:;"> Profile</a></li>

                                <li><a href="javascript:;">Help</a></li>
                                <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                            </ul>
                        </li>


                        <li role="presentation" class="dropdown">
                            <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown"
                               aria-expanded="false">
                                <i class="fa fa-envelope-o"></i>
                                <span class="badge bg-green">6</span>
                            </a>
                            <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                                <li>
                                    <a>
                                        <span class="image"><img src="{% static 'reports/img/img.png' %}" alt="Profile Image"/></span>
                        <span>
                          <span>Admin User</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a>
                                        <span class="image"><img src="{% static 'reports/img/img.png' %}" alt="Profile Image"/></span>
                        <span>
                          <span>Admin User</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a>
                                        <span class="image"><img src="{% static 'reports/img/img.png' %}" alt="Profile Image"/></span>
                        <span>
                          <span>Admin User</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a>
                                        <span class="image"><img src="{% static 'reports/img/img.png' %}" alt="Profile Image"/></span>
                        <span>
                          <span>Admin User</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                        </span>
                                    </a>
                                </li>
                                <li>
                                    <div class="text-center">
                                        <a>
                                            <strong>See All Messages</strong>
                                            <i class="fa fa-angle-right"></i>
                                        </a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
        <!-- /top navigation -->


        <!-- page content -->
        <div class="right_col" role="main">
            <div class="row">
                <div class="col-md-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Reports</h2>
                            <ul class="nav navbar-right panel_toolbox">

                                <li style="float:left;">
                                    <a id="modal-471365" href="#modal-container-471365" role="button" class="btn"
                                       data-toggle="modal"><i class="fa fa-save"></i></a>
                                </li>

                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>


                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content" style="min-height:480px;">

                          <h4>  <a href="{% url 'report' 'date_icount' %}">Incident count Vs. Date</a></h4>
                          <h4>  <a href="{% url 'report' 'district_disaster' %}">Incident count Vs. District</a></h4>

                        </div>
                        <!-- /page content -->

                        <!-- footer content -->
                        <footer>
                            <div class="pull-right">
                                CFR Developed by <a href="https://geoedge.lk">GeoEDGE</a>
                            </div>
                            <div class="clearfix"></div>
                        </footer>
                        <!-- /footer content -->
                    </div>
                </div>


                <script src="{% static 'reports/vendors/jquery/dist/jquery.min.js' %}"></script>
                <script src="{% static 'reports/vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
                <script src="{% static 'reports/js/moment/moment.min.js' %}"></script>
                <script src="{% static 'reports/js/datepicker/daterangepicker.js' %}"></script>


                <script src="{% static 'reports/js/bootstrap-select.min.js' %}"></script>
                <!-- FastClick -->
                <script src="{% static 'reports/vendors/fastclick/lib/fastclick.js' %}"></script>
                <!-- NProgress -->
                <script src="{% static 'reports/vendors/nprogress/nprogress.js' %}"></script>

                <!-- Custom Theme Scripts -->
                <script src="{% static 'reports/js/custom.js' %}"></script>

                <script src="{% static 'reports/js/angular/angular.js' %}"></script>
                <script src="{% static 'reports/js/angular/angular-resource.js' %}"></script>
                <script src="{% static 'reports/js/angular-cookies/angular-cookies.min.js' %}"></script>
                <script src="{% static 'reports/js/reports.js' %}"></script>

</body>
</html>