cfr/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from dashboard import views as dashboard_views
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from tastypie.api import Api
from api.resources import MapResource, LayerResource, IncidentResource, DisasterResource, \
    ValidationResource, GarbledIncidentResource, PhotoResource, AppPhotoResource, UserResource, IncidentLanguageTranslationResource, ProvinceResource, DistrictResource,\
    DsResource, GnResource, QuestionsResource, ChoicesResource, IncidentUserChoicesResource
#ValidationResource, GarbledIncidentResource, UserResource, PhotoResource

api = Api(api_name='v1')
api.register(MapResource())
api.register(LayerResource())
api.register(IncidentResource())
api.register(DisasterResource())
api.register(ValidationResource())
api.register(GarbledIncidentResource())
api.register(UserResource())
api.register(PhotoResource())
api.register(AppPhotoResource())
api.register(IncidentLanguageTranslationResource())
api.register(ProvinceResource())
api.register(DistrictResource())
api.register(DsResource())
api.register(GnResource())
api.register(QuestionsResource())
api.register(ChoicesResource())
api.register(IncidentUserChoicesResource())

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin', include(admin.site.urls)),
    url(r'^api/', include(api.urls)),
    url(r'^incidents/', include('incidents.urls', namespace='incidents')),
    url(r'^maps/', include('maps.urls', namespace='maps')),
    url(r'^charts/', include('charts.urls', namespace='charts')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^$', dashboard_views.index),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.conf.urls import url
from django.contrib.auth.urls import url
from django.contrib.auth.views import logout

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^get_summary/$', views.get_summary, name='get_summary'),
    # url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/admin/login/?next=/dashboard'}, name='logout')
    url(r'^logout/$', logout, name='logout')
]

incidents/urls.py
from django.conf.urls import url
from .tables import IncidentTable

from . import views
from .views import incident_list
from .models import Incident

urlpatterns = [
    url(r'^(?P<language>[\w\-]+)$', views.index, name='index'),
    url(r'^incident_form/(?P<language>[\w\-]+)$', views.incident_form, name='incident_form'),
    #url(r'^incident_list', incident_list.as_view(), name='incident_list'),
    url(r'^incident_list/', incident_list.as_view(), name='incident_list'),
    #url(r'^incident_list', incident_list, name='incident_list'),
    url(r'^incident_save/$', views.incident_save, name='incident_save'),
    url(r'^save_validation/$', views.save_validation, name='save_validation'),
    url(r'^incident_details/(?P<id>[\w\-]+)$', views.incident_details, name='incident_details'),
    url(r'^discard_incident/$', views.discard_incident, name='discard_incident'),
    url(r'^select_questions/$', views.select_questions, name='select_questions'),
    url(r'^send_email/$', views.send_email, name='send_email'),
    url(r'^incident_details_test/$', views.incident_details_test, name='incident_details_test'),
    url(r'^save_app_qs', views.save_app_qs, name='save_app_qs'),
    url(r'^send_mail_app/', views.send_mail_app, name='send_mail_app'),
    url(r'^upload_image/', views.upload_image, name='upload_image'),
    url(r'^image_link/(?P<id>[\w\-]+)$', views.image_link, name='image_link'),

]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_protect, csrf_exempt

from incidents.models import Incident
from django.db.models import Count
import json
from django.core.serializers.json import DjangoJSONEncoder

from django.utils import six
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import user_passes_test
import datetime


# user permission
def permission_required(perm, login_url=None, raise_exception=True):
    def check_perms(user):
        if isinstance(perm, six.string_types):
            perms = (perm, )
        else:
            perms = perm
        if user.has_perms(perms):
            return True
        if raise_exception and user.pk:
            raise PermissionDenied
        return False
    return user_passes_test(check_perms, login_url=login_url)


@permission_required('incidents.view_dashboard', login_url='/admin/login/')
def index(request):
    return render(request, 'dashboard/index.html')


@csrf_exempt
def get_summary(request):
    end_date = datetime.datetime.today().strftime("%Y-%m-%d")
    from_date = (datetime.datetime.today() - datetime.timedelta(days=7)).strftime("%Y-%m-%d")
    total_incidents = Incident.objects.count()
    confirmed_inc_count = Incident.objects.filter(validation__isnull=False).count()

    new_incidents = Incident.objects.filter(reported_date__range=(from_date, end_date)).count()

    non_confirmed_count = total_incidents - confirmed_inc_count
    # incident chart disaster-wise
    chart_data = Incident.objects.filter(province__isnull=False).values('disaster_type__english').annotate(count=Count('id')).order_by('-count')

    province_data = Incident.objects.values('province').annotate(count=Count('id')).order_by('-count')

    data = {'total_incidents': total_incidents,
            'confirmed_inc_count': confirmed_inc_count,
            'non_confirmed_count': non_confirmed_count,
            'new_incidents': new_incidents,
            'chart_data': json.dumps(list(chart_data), cls=DjangoJSONEncoder),
            'province_data': json.dumps(list(province_data), cls=DjangoJSONEncoder)

            }

    return HttpResponse(json.dumps(data, cls=DjangoJSONEncoder), content_type='application/json')

dashboard/templates/dashboard/index.html
{% extends "dashboard/site_header.html" %}
{% load static %}


{% block content %}
<style>
.tile_count {margin-bottom:0;}
.tile_count .tile_stats_count:before {border-left:none;}

</style>
<!-- page content -->
<div class="right_col" ng-app="mapApp" ng-controller="DashboardController" ng-init="init()" role="main">

    <!-- top tiles -->
    <div class="row tile_count">
        <div class="col-md-3 col-sm-3 col-xs-6 tile_stats_count">
       <div style="padding:5px;background:#F17D4A;color:#fff;display:inline-block;width:100%;">
        <div class="col-xs-4" >
            <span  class="count_top"><i class="fa fa-flag" style="font-size:58px;"></i></span>
            </div>
             <div class="col-xs-8">
            <span style="font-size:15px;"> New Incidents</span>
            <div  class="count red" style="color:#fff;" ng-bind="new_incidents"></div>
		</div>
		</div>
        </div>
        <div class="col-md-3 col-sm-4 col-xs-6 tile_stats_count">
         <div style="padding:5px;background:#FFB703;color:#fff;display:inline-block;width:100%;">
         <div class="col-xs-4" >
            <span class="count_top"><i class="fa fa-exclamation-circle" style="font-size:58px;"></i></span>
            </div>
            <div class="col-xs-8">
            <span style="font-size:15px;"> Unconfirmed</span>
            <div class="count blue" style="color:#fff;" ng-bind="non_confirmed"></div>
            </div>
	</div>
        </div>
        
        <div class="col-md-3 col-sm-4 col-xs-6 tile_stats_count">
         <div style="padding:5px;background:#00A300;color:#fff;display:inline-block;width:100%;">
          <div class="col-xs-4" >
            <span class="count_top"><i class="fa fa-check-circle" style="font-size:58px;"></i></span>
            </div>
             <div class="col-xs-8">
             <span style="font-size:15px;">Confirmed</span>
            <div class="count green" style="color:#fff;" ng-bind="confirmed"></div>
             </div>
	</div>
        </div>
        <div class="col-md-3 col-sm-4 col-xs-6 tile_stats_count">
         <div style="padding:5px;background:#603CBA;color:#fff;display:inline-block;width:100%;">
         <div class="col-xs-4" >
            <span class="count_top"><i class="fa fa-map-marker" style="font-size:58px;"></i> </span>
            </div>
             <div class="col-xs-8">
           <span style="font-size:15px;"> Total Incidents</span>
            <div class="count purple" style="color:#fff;" ng-bind="total_incidents"></div>
            </div>
	</div>
        </div>

    </div>
    <!-- /top tiles -->

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">

                <div class="row x_title">
                    <div class="col-md-6">
                        <h3>Disaster Map <span> <a href="{% url 'maps:index' %}" class="btn btn-xs btn-info"
                                                   style="float-right;">Full Map </a></span></h3>
                    </div>
                </div>

                <div class="x_content">
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        <div id="placeholder33" style="height: 260px; display: none" class="demo-placeholder"></div>
                        <div style="width: 100%;">
                            <div id="map" class="map thumbnail" style="height:590px;"></div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-12 bg-white">
                        <div class="x_title">
                            <h2>Affected people by Province</h2>
                            <div class="clearfix"></div>
                        </div>
<div style="height:540px;overflow:auto;">
                        {% verbatim %}

                        <style>

         .progress-bar {width:}


                        </style>

                        <div ng-repeat="inc in province_inc" class="col-md-12 col-sm-12 col-xs-6">
                            <div>
                                <p ng-bind="(inc.province ? inc.province : 'Unknown') + ' Province'"></p>
                                <div class="">

                                    <div class="progress">

                                        <div class="progress-bar" role="progressbar"
                                             aria-valuenow="{{ (inc.count/total_incidents)*100  }}"
                                             aria-valuemin="0" aria-valuemax="100"
                                             style="width:{{ (inc.count/total_incidents)*100  }}%">


                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        {% endverbatim %}
</div>
                        <div class="clearfix"></div>
                    </div>
                </div>

            </div>
            <br/>

            <div class="row">
                <div class="col-md-121">


                    <div class="col-md-12 col-sm-6 col-xs-12">
                        <div class="x_panel tile fixed_height_720 overflow_hidden">
                            <div class="x_title">
                                <h2>Disaster Situation</h2>
                                <ul class="nav navbar-right panel_toolbox">
                                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                    </li>

                                    </li>
                                </ul>
                                <div class="clearfix"></div>
                            </div>
                            <div class="x_content" >
                                <table class="" style="width:100%;">
                                    <tr>

                                    </tr>
                                    <tr>
                                        <td>
                                            <nvd3 options='options' data='data'
                                                  api="api"
                                                  config="{refreshDataOnly: true, deepWatchData: true}"></nvd3>

                                        </td>

                                    </tr>
                                </table>
                                </td>
                                </tr>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <div id="popup" style='width:150px'></div>

        </div></div></div>
        <!-- /page content -->

        {% endblock %}

dashboard/templates/dashboard/site_header.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>CFR</title>

    <!--Common CSS -->
    <link href="{% static 'dashboard/vendors/bootstrap/dist/css/bootstrap.min.css'%} " rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'dashboard/vendors/font-awesome/css/font-awesome.min.css'%}" rel="stylesheet">
     <!-- NProgress -->
    <link href="{% static 'dashboard/vendors/nprogress/nprogress.css' %}" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="{% static 'dashboard/css/custom.css'%}" rel="stylesheet">
    <link href="{% static 'dashboard/css/bootstrap-select.min.css'%}" rel="stylesheet">

    <!--Dashboard -->
     <link href="{% static 'dashboard/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css' %}"
          rel="stylesheet">

    <!--Map-->
     <link href="{% static 'dashboard/vendors/openlayers/ol.css' %}" rel="stylesheet">

    <!--Charts-->
    <link href="{% static 'charts/css/nv.d3.min.css' %}" rel="stylesheet">

    
   

    <!--Incidents-->

<!-- JavaScripts-->
    <!--Common js -->
    <!--Jquery-->
    <script src="{% static 'dashboard/vendors/jquery/dist/jquery.min.js'%}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'dashboard/vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    
    <!-- NProgress -->
    <script src="{% static 'dashboard/vendors/nprogress/nprogress.js' %}"></script>
    

     <!--Angular js -->
    <script src="{% static 'incidents/js/angular/angular.js' %}"></script>
    <script src="{% static 'incidents/js/angular/angular-resource.js' %}"></script>
    <script src="{% static 'incidents/js/angular-cookies/angular-cookies.min.js' %}"></script>

    <!--Map -->
    <script src="{% static 'dashboard/vendors/openlayers/ol.js'%}"></script>
    <script src="{% static 'maps/js/map.js' %}"></script>

    <!--Charts-->
    <script src="{% static 'charts/js/d3.min.js ' %}"></script>
    <script src="{% static 'charts/js/nv.d3.min.js' %}"></script>
    <script src="{% static 'charts/js/angular-nvd3/dist/angular-nvd3.js' %}"></script>
    <script src="{% static 'charts/js/ng-print.js' %}"></script>
    <script src="{% static 'charts/js/chart.js' %}"></script>

    <!--Reports-->
    
     <script src="{% static 'reports/js/moment/moment.min.js' %}"></script>
     <script src="{% static 'reports/js/datepicker/daterangepicker.js' %}"></script>

     <script src="{% static 'dashboard/vendors/angularPrint/angularPrint.js' %}"></script>
     <script src="{% static 'reports/js/reports.js' %}"></script>

    <!--Incidents-->
    <link rel="stylesheet" href="{% static 'dashboard/vendors/fancybox/jquery.fancybox.css'%}" media="screen">
    <script src="{% static 'dashboard/vendors/fancybox/jquery.fancybox.js'%}"></script>
    <script src="{% static 'incidents/js/incident.js' %}"></script>
    <script src="{% static 'dashboard/js/angular-bootstrap-multiselect.js' %}"></script>
    
   <script src="{% static 'dashboard/js/jquery-jsonp-2.4.js' %}"></script>
<script>
$(document).ready(function() {
	moment().format('L');
    $("#today").text(moment().format('l'));
     $("#yesterday").text(moment().subtract(1, 'days').format('l'));
      $("#dbefore").text(moment().subtract(2, 'days').format('l'));
      
       $("#fr").text(moment().subtract(7, 'days').format('l'));
        $("#to").text(moment().subtract(3, 'days').format('l'));
    
     
});
</script>
    <script>
$(document).ready(function(){


    $(".fancybox").fancybox({
        openEffect: "none",
        closeEffect: "none"
    });
});

incident = {'name': '{{ incident.name }}',
            'latitude': '{{ incident.latitude }}',
            'longitude': '{{ incident.longitude }}',
            'disaster_type': '/api/v1/disaster/'+'{{ incident.disaster_type_id }}'+'/',
            'contact_no': '{{ incident.contact_no }}',
            'address': '{{ incident.address }}',
            'synced_date': '{{ incident.synced_date }}',
            'reported_date': '{{ incident.reported_date }}',
            'description': '{{ incident.description }}',
            'district': '{{ incident.district }}',
            'province': '{{ incident.province }}',
            'ds': '{{ incident.ds }}',
            'user': '/api/v1/user/1/'
            };

    </script>

    <style>
.gallery
{
    display: inline-block;
    margin-top: 20px;
}




    </style>
</head>

<body class="nav-md" ng-controller="ChartController" ng-init="init()">
<div class="container body">
    <div class="main_container">
        <div class="col-md-3 left_col">
            <div class="left_col scroll-view">
                <div class="navbar nav_title" style="border: 0;">
                 
                    <a style="font-size:12px;" href="{% url 'dashboard:index' %}" class="site_title">
                    <img src="{% static 'dashboard/img/dirslogo.png' %}" alt="logo" class=""><span style="font-size:25px;"> DIRS</span><br><span style="font-size:10px;">Online Disaster Reporting System</span> 
                    </a>
                </div>

                <div class="clearfix"></div>

                <!-- menu profile quick info -->
                <div class="profile">
                    <div class="profile_pic">
                        <img src="{% static 'incidents/img/img.png' %}" alt="..." class="img-circle profile_img">
                    </div>
                    <div class="profile_info">
                        <span>Welcome,</span>
                        <h2>Admin</h2>
                    </div>
                </div>
                <!-- /menu profile quick info -->

                <br/>
                <!-- sidebar menu -->
                <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                    <div class="menu_section">
                        <h3 style="color:#898989;">----------------------------------------</h3>
                        <ul class="nav side-menu">
                            <li><a href="{% url 'dashboard:index' %}"><i class="fa fa-home"></i> Dashboard </a>

                            </li>
                            <li><a href="{% url 'maps:index' %}"><i class="fa fa-map"></i> Disaster Map </a>

                            </li>

                            <li><a href="{% url 'reports:index' %}"><i class="fa fa-edit"></i> Reports </a>

                            </li>

                            <li><a href="{% url 'charts:index' %}"><i class="fa fa-pie-chart"></i> Charts </a>

                            </li>
                            <li><a href="{% url 'incidents:incident_list' %}"><i class="fa fa-info-circle"></i> Incidents </a>

                            </li>


                        </ul>
                    </div>


                </div>
                <!-- /sidebar menu -->


            </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
            <div class="nav_menu">
                <nav>
                    <div class="nav toggle">
                        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                    </div>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="">
                            <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown"
                               aria-expanded="false">
                                <img src="{% static 'incidents/img/img.png' %}" alt="">Admin
                                <span class=" fa fa-angle-down"></span>
                            </a>
                            <ul class="dropdown-menu dropdown-usermenu pull-right">
                                <li><a href="javascript:;"> Profile</a></li>
                                <li>
                                    <a href="{% url 'dashboard:logout' %}" ><i class="fa fa-sign-out pull-right">

                                    </i>
                                        Log Out
                                    </a>
                                </li>
                            </ul>
                        </li>

                    </ul>
                </nav>
            </div>
        </div>
        <!-- /top navigation -->



{% block content %}{% endblock %}
     <!-- footer content -->
        <footer>
            <div class="pull-right">
                Online Disaster Reporting System Developed by <a href="https://geoedge.lk">GeoEDGE CfR Team</a>
            </div>
            <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
    </div>
</div>

<!-- Custom Theme Scripts -->
    <script src="{% static 'dashboard/js/custom.js' %}"></script>

</body>
</html>